GET http://127.0.0.1:5000/messages

###

GET http://127.0.0.1:5000/messages/cd8834c5-d9a6-4c1b-a236-b8a61703dda8

###

POST http://127.0.0.1:5000/messages
Content-Type: application/json

{
  "firstName": "Texter777",
  "text": "Imposible is nothing",
  "email": "test777@test.test"
}

###

PATCH http://localhost:5000/messages/1
Content-Type: application/json

{
  "firstName": "Texter707",
  "text": "Imp",
  "email": "test707@test.test"
}

###

DELETE http://localhost:5000/messages/1